name: GitHub Secret Workflow
on:
  push:
jobs:
  github-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetching GitHub secret
        run: echo "${{ secrets.PASSWORD_TOKEN }}"
